version: "3.8"

services:
  mysql-jsh:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Asd123^^
      MYSQL_DATABASE: ddbb
      MYSQL_USER: uusseerr
      MYSQL_PASSWORD: Asd123^^
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI
    restart: always
